<?php

namespace App\Console\Commands;

use App\Models\AnonymousAuthor;
use App\Models\City;
use App\Models\Recipe;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Services\ImageService;

class ImportRecipes extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'import:recipes {file}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Import recipes from a JSON file generated by the import 2 process';

    public function __construct(
        private ImageService $imageService
    ) {
        parent::__construct();
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $file = $this->argument('file');

        if (!file_exists($file)) {
            $this->error("File not found: $file");
            return 1;
        }

        $json = file_get_contents($file);
        $recipes = json_decode($json, true);

        if (!$recipes) {
            $this->error("Invalid JSON format");
            return 1;
        }

        $this->info("Found " . count($recipes) . " recipes to import.");

        // Ensure recipes directory exists in public disk
        Storage::disk('public')->makeDirectory('recipes');

        foreach ($recipes as $data) {
            $this->info("Importing: " . $data['name']);

            // 1. Handle Author (Default to Anonymous)
            $authorName = $data['author_name'] ?: 'مجهول';
            $author = AnonymousAuthor::firstOrCreate(['name' => $authorName]);

            // 2. Handle City
            $citySlug = $data['city_slug'];
            $city = City::where('slug', $citySlug)->first();
            if (!$city) {
                $this->warn("City not found for slug: $citySlug. Defaulting to General.");
                $city = City::where('slug', 'general')->first(); // Ensure 'general' exists or handle error
            }

            // 3. Handle Image
            $sourceImagePath = null;
            
            // Try 1: Relative to project root (local dev typical)
            $try1 = base_path('../' . $data['image_path']);
            
            // Try 2: Inside storage/app (production import typical)
            // JSON path: "import 2/images/..."
            $try2 = storage_path('app/' . $data['image_path']);

            // Try 3: Direct path (cwd)
            $try3 = $data['image_path'];

            if (file_exists($try1)) {
                $sourceImagePath = $try1;
            } elseif (file_exists($try2)) {
                $sourceImagePath = $try2;
            } elseif (file_exists($try3)) {
                $sourceImagePath = $try3;
            }

            $storagePath = null;
            if (file_exists($sourceImagePath)) {
                $result = $this->imageService->processFromFile($sourceImagePath);
                if ($result['success']) {
                    $storagePath = $result['path'];
                } else {
                    $this->warn("Failed to process image: " . $result['error']);
                }
            } else {
                $this->warn("Image not found: $sourceImagePath");
            }

            // 4. Create Recipe
            $recipe = Recipe::create([
                'name' => $data['name'],
                'slug' => null, // Let model handle generation
                'image_path' => $storagePath,
                'time_needed' => ['raw' => $data['time_needed']],
                'servings' => $data['servings'],
                'city_id' => $city?->id,
                'user_id' => null,
                'anonymous_author_id' => $author->id,
                'is_anonymous' => true,
                // 'ingredients' => $data['ingredients'], // REMOVED: Handled via syncIngredients
                'steps' => $data['steps'],
                'difficulty' => $data['difficulty'],
                'status' => 'approved',
                'approved_at' => now(),
            ]);

            // 5. Link Ingredients
            $this->syncIngredients($recipe, $data['ingredients']);
        }

        $this->info("Import completed successfully.");
        return 0;
    }

    /**
     * Sync ingredients with detailed pivot data.
     * Copied/Adapted from RecipeController.
     */
    private function syncIngredients(Recipe $recipe, array $ingredients): void
    {
        $syncData = [];
        $idsToSync = [];

        foreach ($ingredients as $key => $value) {
            // Handle grouped ingredients: "Sauce" => [ {name: "Tomato", ...}, ... ]
            if (is_string($key) && is_array($value)) {
                $groupName = $key;
                foreach ($value as $item) {
                    $this->processIngredientItem($item, $syncData, $groupName);
                }
            } 
            // Handle flat list items
            else {
                $this->processIngredientItem($value, $syncData);
            }
        }

        $recipe->ingredients()->sync($syncData);
    }

    private function processIngredientItem(array|string $item, array &$syncData, ?string $group = null): void
    {
        if (is_string($item)) {
            $name = $item;
            $amount = null;
            $unit = null;
            $descriptor = null;
        } else {
            $name = $item['name'] ?? null;
            $amount = $item['amount'] ?? null;
            $unit = $item['unit'] ?? null;
            $descriptor = $item['descriptor'] ?? null;
            $group = $item['group'] ?? $group;
        }

        if (!$name) return;

        $normalized = \App\Models\Ingredient::normalize($name);
        
        $ingredient = \App\Models\Ingredient::firstOrCreate(
            ['normalized_name' => $normalized],
            ['name' => $name]
        );

        $syncData[$ingredient->id] = [
            'amount' => $amount,
            'unit' => $unit,
            'ingredient_descriptor' => $descriptor,
            'group' => $group,
        ];
    }
}
